knee_orientation : "<<"
pantograph_leg : false
max_linear_velocity_x : 0.25 # default 0.5
max_linear_velocity_y : 0.25
max_angular_velocity_z : 1.0
com_x_translation : -0.05 # default 0
swing_height : 0.04
stance_depth : 0.0
stance_duration : 0.3 # default 0.25
nominal_height : 0.2